# Generated by Django 2.2.10 on 2020-05-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
