# Generated by Django 2.2.10 on 2020-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200514_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post-default.jpg', upload_to='blog/post'),
        ),
    ]
